### ISSUE TITLE
티스토리 글 발행 명령 후 팝업창이 제대로 뜨지 않습니다

### ISSUE THREAD

**Issue by gcount85** [anpigon/obsidian-tistory-plugin#1]
안녕하세요! 
방금 플러그인을 설치하고 테스트했는데 다음과 같이 팝업창의 옵션이 보이지 않아요. 
![image](https://user-images.githubusercontent.com/54928040/197242446-65e16025-1e58-4ca4-9ee8-dfe26bbad260.png)

구글링하다가 여기까지 오게 됐습니다.
꼭 필요하던 기능이었는데 만들어주셔서 감사합니다.

**Comment by anpigon** [comment]
이슈 올려주셔서 감사합니다. 옵시디언이 v1.0.0으로 업데이트 되면서 플러인에 문제가 발생한 것 같습니다. 빠른 시일내에 대응할 예정입니다.
관심 가져주셔서 감사합니다.

**Comment by jeongsk** [comment]
@gcount85 해당 문제에 대해서 살펴봤습니다. 하지만 정확한 재현 경로와 문제의 원인을 찾을 수가 없었어요. 
혹시 가능하다면 실행 환경 또는 정확한 증상을 알려주시면 이슈를 해결하는데 많은 도움이 될 것 같습니다.
감사합니다.

**Comment by anpigon** [comment]
@gcount85
제가 사용중인 노트북에서는 해당 문제가 발생하지 않아서 해결하지 못했습니다.ㅠ
가능하다면 실행환경이나 자세한 증상을 알려주시면 문제를 해결하는데 많은 도움이 될 것 같습니다.
감사합니다.

**Comment by gcount85** [comment]
@anpigon 플러그인 설정에서 티스토리와 연결 후, 노트에서 명령을 실행하면 모달창의 옵션들이 0.5초 정도 보였다가 사라지면서 저렇게 헤더 부분만 보입니다. 
윈도우11에서 v1.0.3 사용 중이구요.. 새로운 valut를 만들어서 테스트해봤는데 동일합니다.

**Comment by anpigon** [comment]
> @anpigon 플러그인 설정에서 티스토리와 연결 후, 노트에서 명령을 실행하면 모달창의 옵션들이 0.5초 정도 보였다가 사라지면서 저렇게 헤더 부분만 보입니다. 윈도우11에서 v1.0.3 사용 중이구요.. 새로운 valut를 만들어서 테스트해봤는데 동일합니다.

@gcount85님 해당 이슈를 발견하여 해결하였습니다. 플러그인을 v0.2.4으로 업데이트하면 됩니다.
