### ISSUE TITLE
Fix book search obsidian plugin please. / 도서 검색 흑요석 플러그인을 수정해 주세요.

### ISSUE THREAD

**Issue by BusterBlade5** [anpigon/obsidian-tistory-plugin#6]
The book search plugin stopped working with the new properties update. Can you fix it, please?
새로운 속성 업데이트로 인해 책 검색 플러그인이 작동하지 않습니다. 고쳐주실 수 있나요?

**Comment by anpigon** [comment]
I've been very busy lately and haven't been paying attention to plugins.
Thanks for letting me know in the comments.
